# 头部菜单，title: link
menu:
  Whoami: /whoami
  Github: https://github.com/Clarence-Kong
  分类: /categories
  归档: /archives
  标签云: /tags

# 是否显示目录
TOC: false

# 是否自动播放音乐
autoplay: false

# 默认音乐（随机播放）
mp3:
  - http://link.hhtjim.com/163/425570952.mp3
  - http://link.hhtjim.com/163/425570952.mp3

# 首页封面图, 为空时取文章的cover作为封面
welcome_cover: # /img/welcome-cover.jpg

# 默认文章封面图
cover: http://s1.wailian.download/2020/01/11/dark_masks_PayDay_wolves_Payday_The_Heist_PayDay_2_the_heist_1920x1080.jpg

# Gitalk 评论插件（https://github.com/gitalk/gitalk）
gitalk:
  # 是否自动展开评论框
  autoExpand: false
  # 应用编号
  clientID: ''
  # 应用秘钥
  clientSecret: ''
  # issue仓库名
  repo: 'Clarence-Kong'
  # Github名
  owner: 'Clarence-Kong'
  # Github名
  admin: ['Clarence-Kong']
  # Ensure uniqueness and length less than 50
  id: location.pathname
  # Facebook-like distraction free mode
  distractionFreeMode: false

# 网站关键字
keywords: Clarence-Kong,博客

# 要使用google_analytics进行统计的话，这里需要配置ID
google_analytics:

# 网站ico
favicon: /img/favicon.png

# rss文件
rss: atom.xml
